apiVersion: apps/v1
kind: Deployment
metadata:
  name: mineral-classifier
  namespace: mineral-classifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mineral-classifier
  template:
    metadata:
      labels:
        app: mineral-classifier
    spec:
      containers:
      - name: mineral-classifier
        image: gimmyhat/mineral-classifier:latest
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: mineral-classifier-config
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: results
          mountPath: /app/results
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: app-data-pvc
      - name: results
        persistentVolumeClaim:
          claimName: app-results-pvc 