version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - ./Справочник_для_редактирования_09.10.2024.xlsx:/app/Справочник_для_редактирования_09.10.2024.xlsx
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=minerals
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=minerals
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d minerals"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: