apiVersion: v1
kind: Service
metadata:
  name: mineral-classifier
  namespace: mineral-classifier
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8001
  selector:
    app: mineral-classifier 