apiVersion: apps/v1
kind: Deployment
metadata:
  name: mineral-classifier-redis
  namespace: mineral-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mineral-classifier-redis
  template:
    metadata:
      labels:
        app: mineral-classifier-redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc 